[package]
name = "wifi-party-rust"
version = "0.1.0"
authors = ["ken <39673849+SuperKenVery@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = ["desktop"] }
cpal = "0.15"
rkyv = "0.8"
rtrb = "0.3"
socket2 = "0.5"
crossbeam-channel = "0.5"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1", features = ["full"] }
dasp_sample = "0.11"

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
