[application]
android_manifest = "assets/AndroidManifest.xml"
android_main_activity = "assets/MainActivity.kt"

[bundle]
identifier = "com.ken.WifiPartyRust"
publisher = "ken"
icon = []
resources = []

[bundle.macos]
info_plist_path = "assets/Info.plist"

[permissions]
microphone.description = "Wi-Fi Party needs microphone permission to send your voice to the network"

[web.app]

# HTML title tag content
title = "wifi-party-rust"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
